function registerPlayer ( password, age, nationality, page, icq, mail, sex )
	if ( password ~= "" and password ~= nil ) then
				if(xmlLoadFile ( ":players/Accounts/"..tostring(getPlayerName(source))..".xml" ) ) then
				    outputChatBox ( "Данный аккаунт уже зарегистрирован!",source )
				else
					local RootNode = xmlCreateFile ( ":players/Accounts/"..tostring(getPlayerName(source))..".xml", "source" )
	     			local plpass = xmlCreateChild ( RootNode, "password" )
	     			xmlNodeSetValue ( plpass, ""..tostring(password).."" )
					local xmlFileID = xmlLoadFile ( "ID.xml" )
					local idnumber = xmlFindChild ( xmlFileID, "id", 0 )
					numberid = xmlNodeGetValue ( idnumber )
					local idn = numberid + 1
					local plid = xmlCreateChild ( RootNode, "id" )
	     			xmlNodeSetValue ( plid, ""..tostring(idn).."" )
					xmlNodeSetValue ( idnumber, tostring(idn) )
    				xmlSaveFile ( xmlFileID )
					local plmoney = xmlCreateChild ( RootNode, "money" )
	     			xmlNodeSetValue ( plmoney, "10000" )
	     			local plbmoney = xmlCreateChild ( RootNode, "bmoney" )
	     			xmlNodeSetValue ( plbmoney, "50000" )
	     			local pldrive = xmlCreateChild ( RootNode, "drive" )
	     			xmlNodeSetValue ( pldrive, "0" )
	     			local plfly = xmlCreateChild ( RootNode, "fly" )
	     			xmlNodeSetValue ( plfly, "0" )
	     			local plboat = xmlCreateChild ( RootNode, "boat" )
	     			xmlNodeSetValue ( plboat, "0" )
	     			local pladm = xmlCreateChild ( RootNode, "admin" )
	     			xmlNodeSetValue ( pladm, "0" )
	     			local plrp = xmlCreateChild ( RootNode, "rplvl" )
	     			xmlNodeSetValue ( plrp, "0" )
	     			local plwarn = xmlCreateChild ( RootNode, "warn" )
	     			xmlNodeSetValue ( plwarn, "0" )
	     			local plfaction = xmlCreateChild ( RootNode, "faction" )
	     			xmlNodeSetValue ( plfaction, "0" )
	     			local plrank = xmlCreateChild ( RootNode, "rank" )
	     			xmlNodeSetValue ( plrank, "0" )
	     			local plphone = xmlCreateChild ( RootNode, "phone" )
	     			xmlNodeSetValue ( plphone,  "0" )
	     			local plpmoney = xmlCreateChild ( RootNode, "pmoney" )
	     			xmlNodeSetValue ( plpmoney, "0" )
	     			local plwork = xmlCreateChild ( RootNode, "work" )
	     			xmlNodeSetValue ( plwork, "0" )
	     			local plage = xmlCreateChild ( RootNode, "age" )
	     			xmlNodeSetValue ( plage, age )
	     			local plskin = xmlCreateChild ( RootNode, "skin" )
	     			xmlNodeSetValue ( plskin, "7" )
	     			local plpass = xmlCreateChild ( RootNode, "passport" )
	     			xmlNodeSetValue ( plpass, "0" )
	     			local plcrimes = xmlCreateChild ( RootNode, "crimes" )
	     			xmlNodeSetValue ( plcrimes, "0" )
	     			local plarrest = xmlCreateChild ( RootNode, "arrest" )
	     			xmlNodeSetValue ( plarrest, "0" )
	     			local plweap = xmlCreateChild ( RootNode, "weapons" )
	     			xmlNodeSetValue ( plweap, "0" )
	     			local plweapmat = xmlCreateChild ( RootNode, "weapmat" )
	     			xmlNodeSetValue ( plweapmat, "0" )
	     			local pldrugs = xmlCreateChild ( RootNode, "drugs" )
	     			xmlNodeSetValue ( pldrugs, "0" )
	     			local plorigin = xmlCreateChild ( RootNode, "origin" )
	     			xmlNodeSetValue ( plorigin, "0" )
	     			local plsocnik = xmlCreateChild ( RootNode, "house" )
	     			xmlNodeSetValue ( plsocnik, "0" )
	     			local plicq = xmlCreateChild ( RootNode, "icq" )
	     			xmlNodeSetValue ( plicq, icq )
	     			local plmail = xmlCreateChild ( RootNode, "e-mail" )
	     			xmlNodeSetValue ( plmail, mail )
	     			local plintel = xmlCreateChild ( RootNode, "intel" )
	     			xmlNodeSetValue ( plintel, "0" )
	     			local plluck = xmlCreateChild ( RootNode, "luck" )
	     			xmlNodeSetValue ( plluck, "0" )
	     			local plvision = xmlCreateChild ( RootNode, "vision" )
	     			xmlNodeSetValue ( plvision, "0" )
	     			local plhealth = xmlCreateChild ( RootNode, "health" )
	     			xmlNodeSetValue ( plhealth, "0" )
	     			local plclap = xmlCreateChild ( RootNode, "clap" )
	     			xmlNodeSetValue ( plclap, "0" )
	     			local pltie = xmlCreateChild ( RootNode, "tie" )
	     			xmlNodeSetValue ( pltie, "0" )
	     			local plmask = xmlCreateChild ( RootNode, "mask" )
	     			xmlNodeSetValue ( plmask, "0" )
	     			local plaptecka = xmlCreateChild ( RootNode, "aptecka" )
	     			xmlNodeSetValue ( plaptecka, "0" )
	     			local plsex = xmlCreateChild ( RootNode, "sex" )
	     			xmlNodeSetValue ( plsex, "0" )
	     			local plnat = xmlCreateChild ( RootNode, "nat" )
	     			xmlNodeSetValue ( plnat, nationality )
	     			local plage = xmlCreateChild ( RootNode, "page" )
	     			xmlNodeSetValue ( plage, page )
	     			local plnwkey = xmlCreateChild ( RootNode, "nwkey" )
	     			xmlNodeSetValue ( plnwkey, "0" )
	     			local plsckey = xmlCreateChild ( RootNode, "sckey" )
	     			xmlNodeSetValue ( plsckey, "0" )
	     			local plnation = xmlCreateChild ( RootNode, "nation" )
	     			xmlNodeSetValue ( plnation, "1" )
	     			local plvirus = xmlCreateChild ( RootNode, "virus" )
	     			xmlNodeSetValue ( plvirus, "0" )
	     			local plav1 = xmlCreateChild ( RootNode, "rentcar" )
	     			xmlNodeSetValue ( plav1, "0" )
	     			local plav2 = xmlCreateChild ( RootNode, "av2" )
	     			xmlNodeSetValue ( plav2, "0" )
	     			local plrad = xmlCreateChild ( RootNode, "rad" )
	     			xmlNodeSetValue ( plrad, "0" )
	     				     			local plweap1 = xmlCreateChild ( RootNode, "weap1" )
	     			xmlNodeSetValue ( plweap1, "0" )
	     			local plweap2 = xmlCreateChild ( RootNode, "weap2" )
	     			xmlNodeSetValue ( plweap2, "0" )
	     			local plweap3 = xmlCreateChild ( RootNode, "weap3" )
	     			xmlNodeSetValue ( plweap3, "0" )                 
	     			local plweap4 = xmlCreateChild ( RootNode, "weap4" )
	     			xmlNodeSetValue ( plweap4, "0" )
	     			local plweap5 = xmlCreateChild ( RootNode, "weap5" )
	     			xmlNodeSetValue ( plweap5, "0" )
	     			local plweap6 = xmlCreateChild ( RootNode, "weap6" )
	     			xmlNodeSetValue ( plweap6, "0" )
	     			local plweap7 = xmlCreateChild ( RootNode, "weap7" )
	     			xmlNodeSetValue ( plweap7, "0" )
	     			local plweap8 = xmlCreateChild ( RootNode, "weap8" )
	     			xmlNodeSetValue ( plweap8, "0" )
	     			local plweap9 = xmlCreateChild ( RootNode, "weap9" )
	     			xmlNodeSetValue ( plweap9, "0" )
	     			local plweap10 = xmlCreateChild ( RootNode, "weap10" )
	     			xmlNodeSetValue ( plweap10, "0" )
	     			local plammo1 = xmlCreateChild ( RootNode, "ammo1" )
	     			xmlNodeSetValue ( plammo1, "0" )
	     			local plammo2 = xmlCreateChild ( RootNode, "ammo2" )
	     			xmlNodeSetValue ( plammo2, "0" )
	     			local plammo3 = xmlCreateChild ( RootNode, "ammo3" )
	     			xmlNodeSetValue ( plammo3, "0" )
	     			local plammo4 = xmlCreateChild ( RootNode, "ammo4" )
	     			xmlNodeSetValue ( plammo4, "0" )
	     			local plammo5 = xmlCreateChild ( RootNode, "ammo5" )
	     			xmlNodeSetValue ( plammo5, "0" )
	     			local plammo6 = xmlCreateChild ( RootNode, "ammo6" )
	     			xmlNodeSetValue ( plammo6, "0" )
	     			local plammo7 = xmlCreateChild ( RootNode, "ammo7" )
	     			xmlNodeSetValue ( plammo7, "0" )
	     			local plammo8 = xmlCreateChild ( RootNode, "ammo8" )
	     			xmlNodeSetValue ( plammo8, "0" )
	     			local plammo9 = xmlCreateChild ( RootNode, "ammo9" )
	     			xmlNodeSetValue ( plammo9, "0" )
	     			local plammo10 = xmlCreateChild ( RootNode, "ammo10" )
	     			xmlNodeSetValue ( plammo10, "0" )
	     			local spx = xmlCreateChild ( RootNode, "spx" )
	     			xmlNodeSetValue ( spx, "0" )
                    local spy = xmlCreateChild ( RootNode, "spy" )
	     			xmlNodeSetValue ( spy, "0" )
	     			local spz = xmlCreateChild ( RootNode, "spz" )
	     			xmlNodeSetValue ( spz, "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "bunk1" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "bunk2" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "bunk3" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "bunk4" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "bunk5" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "bunk6" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "bunk7" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "bunk8" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "bunk9" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "bunk10" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "bunk11" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "bunk12" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "bunk13" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "bunk14" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "bunk15" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "bunk16" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "bunk17" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "bunk18" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "bunk19" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "bunk20" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "totalbunks" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "ach1" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "ach2" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "ach3" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "ach4" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "ach5" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "ach6" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "ach7" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "ach8" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "ach9" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "ach10" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "ach11" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "ach12" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "ach13" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "ach14" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "ach15" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "ach16" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "ach17" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "ach18" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "ach19" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "ach20" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "ach21" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "ach22" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "ach23" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "points" ), "0" )
	     			xmlNodeSetValue (xmlCreateChild ( RootNode, "houserent" ), "0" )
					xmlSaveFile ( RootNode )
					xmlSaveFile ( RootNode )
					addAccount( getPlayerName(source), password )
					outputChatBox ( "Вы успешно зарегистрировались на нашем сервере!",source )
				end
	else
		outputChatBox ( "Error creating account, correct syntax: /register <password>", source )
	end
end

addEvent( "finRegisterPlayer", true )
addEventHandler( "finRegisterPlayer", getRootElement(), registerPlayer )